In [51]:
l = [
    [1, 0, 0, 0],
    [0, 0, 0, 1], 
    [0, 1, 0, 0],
]

In [52]:
import numpy as np

k = 2
l = l[1]
s = np.asarray(l)[:k]
s

array([0, 0])

In [53]:
rs = np.asarray(s).nonzero()[0]
list(rs)

[]

In [54]:
mrr = 1/(rs + 1)
mrr

array([], dtype=float64)

In [55]:
0 if mrr.size == 0 else mrr.mean()

0

In [44]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv('/media/workspace/triplet_session/output/globo/dataset/test_0.01_test=time_42_SessionInteractionDataFrame_AvailableItems____SessionID_e0d2ef69e8.csv')

In [46]:
df.shape

(176684, 9)

In [47]:
_df = df[['SessionID', 'ItemID', 'visit']]
_df

SessionID  ItemID  visit
0       1508035475924790  293334      1
1       1508036239928993  312922      1
2       1508036369163023  299131      1
3       1508031505377466  343256      1
4       1508034075267382  324272      1
...                  ...     ...    ...
176679  1508205185244493  234978      1
176680  1508204173113977  211442      1
176681  1508204800214313   36162      1
176682  1508204554122178  277107      1
176683  1508205226121508   36162      1

[176684 rows x 3 columns]

In [48]:
from scipy.sparse import csr_matrix
from pandas.api.types import CategoricalDtype


In [49]:
sparse_matrix

<3476x98998 sparse matrix of type '<class 'numpy.int64'>'
	with 176684 stored elements in Compressed Sparse Row format>

In [50]:
sparse_matrix[0]

<1x98998 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [55]:
dot = sparse_matrix[0] * sparse_matrix[2].T

In [56]:
sim = np.array(dot.T.todense())[0]
sim

array([0])

In [57]:
sim[0]

0

In [40]:
sorted(sim)[-20:]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 14]

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity

<function sklearn.metrics.pairwise.cosine_similarity(X, Y=None, dense_output=True)>

In [66]:
cosine_similarity(sparse_matrix[0].todense(), sparse_matrix[0].todense())[0][0]

1.0

In [68]:
cosine_similarity(sparse_matrix).shape

(3476, 3476)

In [5]:
df_pivot = pd.pivot_table(df, values='visit', index='SessionID', columns='ItemID').fillna(0)
df_pivot

ItemID            1779    1844    1873    1895    1932    1946    1975    \
SessionID                                                                  
1507038888589172     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1507045423338235     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1507116847148219     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1507119319339945     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1507148167808971     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...                  ...     ...     ...     ...     ...     ...     ...   
1508205507274621     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1508205517267623     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1508205520266626     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1508205527242632     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1508205549262639     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

ItemID            2055    2134    2158    ...  363068  363080  363139  363185  \
SessionID                                 ...                                   
1507038888589172     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1507045423338235     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1507116847148219     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1507119319339945     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1507148167808971     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
...                  ...     ...     ...  ...     ...     ...     ...     ...   
1508205507274621     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1508205517267623     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1508205520266626     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1508205527242632     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   
1508205549262639     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0   

ItemID            363188  363216  363246  363916  363967  364017  
SessionID                                                         
1507038888589172     0.0     0.0     0.0     0.0     0.0     0.0  
1507045423338235     0.0     0.0     0.0     0.0     0.0     0.0  
1507116847148219     0.0     0.0     0.0     0.0     0.0     0.0  
1507119319339945     0.0     0.0     0.0     0.0     0.0     0.0  
1507148167808971     0.0     0.0     0.0     0.0     0.0     0.0  
...                  ...     ...     ...     ...     ...     ...  
1508205507274621     0.0     0.0     0.0     0.0     0.0     0.0  
1508205517267623     0.0     0.0     0.0     0.0     0.0     0.0  
1508205520266626     0.0     0.0     0.0     0.0     0.0     0.0  
1508205527242632     0.0     0.0     0.0     0.0     0.0     0.0  
1508205549262639     0.0     0.0     0.0     0.0     0.0     0.0  

[98998 rows x 3476 columns]

In [6]:
import gc; gc.collect()

0

In [7]:
df_pivot.iloc[0].values#.ItemID#.values()

array([0., 0., 0., ..., 0., 0., 0.])

In [12]:
item_idx = list(df_pivot.columns)
np.min(item_idx)

1779

In [13]:
coocc = df_pivot.T.dot(df_pivot)
coocc

ItemID  1779    1844    1873    1895    1932    1946    1975    2055    \
ItemID                                                                   
1779       1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1844       0.0    11.0     0.0     0.0     0.0     0.0     0.0     0.0   
1873       0.0     0.0    14.0     0.0     0.0     0.0     0.0     0.0   
1895       0.0     0.0     0.0     3.0     0.0     0.0     1.0     0.0   
1932       0.0     0.0     0.0     0.0     8.0     0.0     0.0     0.0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
363216     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
363246     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
363916     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
363967     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
364017     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

ItemID  2134    2158    ...  363068  363080  363139  363185  363188  363216  \
ItemID                  ...                                                   
1779       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
1844       0.0     0.0  ...     1.0     0.0     0.0     0.0     0.0     0.0   
1873       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
1895       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
1932       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...     ...  ...     ...     ...     ...     ...     ...     ...   
363216     0.0     0.0  ...     0.0     0.0     0.0     1.0     0.0     2.0   
363246     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
363916     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
363967     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
364017     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

ItemID  363246  363916  363967  364017  
ItemID                                  
1779       0.0     0.0     0.0     0.0  
1844       0.0     0.0     0.0     0.0  
1873       0.0     0.0     0.0     0.0  
1895       0.0     0.0     0.0     0.0  
1932       0.0     0.0     0.0     0.0  
...        ...     ...     ...     ...  
363216     0.0     0.0     0.0     0.0  
363246     2.0     0.0     0.0     0.0  
363916     0.0   354.0     0.0     0.0  
363967     0.0     0.0     1.0     0.0  
364017     0.0     0.0     0.0     1.0  

[3476 rows x 3476 columns]

In [14]:
np.fill_diagonal(coocc.values, 0)

In [19]:
coocc.iloc[0].idxmax()

101991